---

version: 0.9.2-{build}

configuration: Release
image: Visual Studio 2022
platform: x64

cache: 
    - c:\hunter\ -> appveyor.yml

build:
    verbosity: minimal


install:
    - set PATH=C:\Strawberry\perl\bin;C:\Python39-x64;%QT_DIR%\bin;%PATH%

build_script:
    - cmake --version

    - cmake -G "Visual Studio 17 2022" -H. -Bbuild -DHUNTER_ENABLED=ON -DHUNTER_ROOT="C:\hunter"
      -DCMAKE_BUILD_TYPE=Release -DHUNTER_CONFIGURATION_TYPES=Release -DUSE_BUNDLED_GTEST=OFF -DBUILD_LIB_TESTS=OFF -DBUILD_LIB_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF
    - cmake --build build --config Release
